# Generated by Django 5.0.6 on 2024-06-23 14:03

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Boleta',
            fields=[
                ('id_boleta', models.AutoField(primary_key=True, serialize=False)),
                ('total', models.BigIntegerField()),
                ('fechaCompra', models.DateTimeField(default=datetime.datetime.now)),
            ],
        ),
        migrations.CreateModel(
            name='Envoltura',
            fields=[
                ('idCategoria', models.IntegerField(primary_key=True, serialize=False, verbose_name='Id de categoria')),
                ('nombreCategoria', models.CharField(max_length=50, verbose_name='Nombre de categoria')),
            ],
        ),
        migrations.CreateModel(
            name='Roll',
            fields=[
                ('idRool', models.IntegerField(primary_key=True, serialize=False, verbose_name='Id de roll')),
                ('nombreRool', models.CharField(max_length=255, verbose_name='Nombre de roll')),
                ('descripcionRool', models.CharField(max_length=255, verbose_name='Descripcion')),
                ('stockRoll', models.IntegerField()),
                ('imagenRool', models.ImageField(null=True, upload_to='imagenes', verbose_name='Imagen de roll')),
                ('precioRoll', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Precio del roll')),
                ('Envoltura', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='productos.envoltura', verbose_name='Envoltura')),
            ],
        ),
        migrations.CreateModel(
            name='detalle_boleta',
            fields=[
                ('id_detalle_boleta', models.AutoField(primary_key=True, serialize=False)),
                ('cantidad', models.IntegerField()),
                ('subtotal', models.BigIntegerField()),
                ('id_boleta', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='productos.boleta')),
                ('id_producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='productos.roll')),
            ],
        ),
    ]
