# Generated by Django 5.0.6 on 2024-06-23 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roll',
            name='precioRoll',
            field=models.IntegerField(blank=True, null=True, verbose_name='Precio del roll'),
        ),
    ]
